stud_name=input("Student Name :")
py_score=float(input("Python Score :"))
eng_score=float(input("English Score :"))
math_score=float(input("Mathematics Score :"))
avg_score=(py_score+eng_score+math_score)/3
print("========================================")
print("\t STUDENT RESULT")
print("========================================")
print("\n Student :" +stud_name)
print(f"\n Python :\t {py_score}")
print(f"English : \t {eng_score}")
print(f"Mathematics : \t {math_score}")
print("--------------------------------------")
print(f"Average : \t {avg_score}")
print("=========================================")