name=input("Enter your name :")
weight=float(input("Enter your weight in kg :"))
height=float(input("Enter your height in meter :"))
BMI=weight/(height*height)
print("================================")
print("\t BMI REPORT")
print("================================")
print("Name : " + name)
print(f"Weight : {weight} kg")
print(f"Height : {height} m")
print(f"\n BMI : {BMI}")
print("================================")